@startuml Durak Spiel

skinparam{
    ClassBackgroundColor white
    ClassBorderColor black

    'ClassAttributeIconSize 0

    ArrowColor black

    Shadowing false

}

class Spiel {
    -spieler: Spieler[]
    -timer: Int
    -verteidiger: Spieler
    -angreifer: Spieler
    -trumpf: Farbe
    -tischKarten: Angriffskarten:Verteidigungskarten{}
    -rangliste: Spieler:Punkte{}

    -spielStarten(regeln, trumpf) : Deck
    -zugBeenden()
    -verteidigerDeffinieren()
    -angreiferDeffinieren()
}

class Spieler {
    +name : String
    +rolle: Rolle
    -hand: Karte[]

    -karteLegen(Karte)
}

class Karte {
    -farbe: Farbe
    -wert: Wert
}

class Joker {
    -jokerFunktion()
}

class Deck {
    -karten: Karte[]

    -trumphwertSetzen()
    +kartenGeben(anz) : Karte[]
}

enum Farbe {
    - Herz 
    - Karo 
    - Pic 
    - Kreuz
}

enum Rolle {
    - Verteidiger
    - Angreifer
}

Spiel "1" *-- "2..5" Spieler

Spiel "1" *-- "1" Deck

Deck "1" *-- "36..40" Karte

Karte <|-- "4" Joker 

Spieler "1" o-- "0..40" Karte 

@enduml