@startuml Durak Lobby

skinparam{
    ClassBackgroundColor white
    ClassBorderColor black

    'ClassAttributeIconSize 0

    ArrowColor #404040
    ArrowFontColor #000050

    Shadowing false

}

class Spieler {
    +name : String
    -passwort: String
    -mail: String
    -eigenesSpiel: Spiel
    -spielregelnDefinieren(eigenesSpiel)
    -spielStarten(eigenesSpiel)
    -spielLoeschen(eigenesSpiel)
    -spielBeitreten()
}
note left
    Rollen:
    Mitspieler 
    Spiel-Ersteller
end note

class Lobby {
    +offeneSpiele: Spiel[]
    +anwesendeSpieler: Spieler[]
    -registrieren(name, mail, pwd)
    -einloggen(name, pwd)
    -ausloggen(Spieler)
    -spielStarten(Spiel)
}

class Spiel {
    + maxSpieler: Spieleranzahl
    + anwesendeSpieler: Spieler[]
    + regeln: Spielregeln
}

class Spielregeln {
    + joker: Jokerfunktion
    + einzelrunde: Bool
    + zeitProKarte: Int
}

class Chat {
    + nachrichtenPosten(nachricht)
    + privateNachrichtPosten(Spieler, nachricht)
}

enum Jokerfunktion {
    -kein Joker
    -Handkarte und Rolle tauschen
    -höher als Ass
}

enum Spieleranzahl {
    - 2
    - 3
    - 4
    - 5
}



Lobby "1" o-- "0..*" Spieler : hat >

Spieler "1..5" --* "1" Spiel : tritt bei oder erstellt >

Spiel "1" --* "1" Spielregeln : hat >

Lobby "1" *-- "0..*" Spiel : verwaltet >

Spieler "0..*" -- "1" Chat : nutzt >

Lobby "1" *-- "1" Chat : verwaltet >

Spieler "0..1" -- "1" Spielregeln: definiert > 

@enduml