@startuml Durak Spiel

skinparam{
    ClassBackgroundColor white
    ClassBorderColor black

    'ClassAttributeIconSize 0

    ArrowColor #404040
    ArrowFontColor #000050

    Shadowing false

}

class Spiel {
    -spieler: Spieler[]
    -timer: Int
    -verteidiger: Spieler
    -angreifer: Spieler
    -trumpf: Farbe
    -regeln: Spielregeln
    -deck: Deck
    +tischKarten: Angriffskarten:Verteidigungskarten{}
    +rangliste: Spieler:Punkte{}

    -spielStarten(regeln, trumpf) : Deck
    + zugBeenden()
    -verteidigerDefinieren(angreifer)
    -angreiferDefinieren(verteidiger)
    -schieben()
    +karteValidieren(Karte, Spieler, Zielkarte) : Bool
}

class Spielregeln {
    + joker: Jokerfunktion
    + einzelrunde: Bool
    + zeitProKarte: Int
}

class Spieler {
    +name : String
    -passwort : String
    -mail : String
    +rolle: Rolle
    +hand: Karte[]

    -karteLegen(Karte, Zielkarte)
    -spielVerlassen()
}

class Karte {
    -farbe: Farbe
    -wert: Wert
}

class Joker {
    -jokerFunktion()
}

class Deck {
    -karten: Karte[]
    
    -mischen(regeln) : Karte[]
    -trumphwertSetzen(trumph)
    +kartenGeben(anz) : Karte[]
}

enum Farbe {
    - Herz 
    - Karo 
    - Pic 
    - Kreuz
}

enum Rolle {
    - Keine  
    - Verteidiger
    - Angreifer
}

enum Jokerfunktion {
    -kein Joker
    -Handkarte und Rolle tauschen
    -höher als Ass
}


Spiel "1" o-- "2..5" Spieler : spielt <

Spiel "1" o-- "1" Deck : hat >

Deck "1" o-- "0..40" Karte : hat >

Karte <|-- "4" Joker 

Spieler "1" o-- "0..40" Karte : hat auf der Hand >

Spiel "1" o-- "1" Spielregeln : hat >

Deck "1" -- "1" Spielregeln : braucht zum mischen >


@enduml