@startuml
left to right direction

skinparam{
    UsecaseBackgroundColor white
    UsecaseBorderColor black

    ArrowColor black

    Shadowing false

    ActorBackgroundColor white
    ActorBorderColor black
}

actor :Spieler: as Spieler
actor :Angreifer: as Angreifer
actor :Verteidiger: as Verteidiger
actor :Spielleiter: as Leiter
actor :1. Angreifer: as a1


rectangle Spiel {
    (Zug eröffnen) as start
    (Spiel verlassen) as verlassen
    (Spiel beenden) as beenden
    (angreifen)
    (verteidigen)
    (schieben)
    (nachziehen)
}

Angreifer --|> Spieler
Verteidiger --|> Spieler
Leiter --|> Spieler
a1 --|> Angreifer

Spieler -- verlassen
Spieler -- nachziehen
Angreifer -- angreifen
Verteidiger -- verteidigen
Verteidiger -- schieben

a1 -- start 

Leiter -- beenden

verlassen .> beenden : <<extend>>

@enduml