@startuml

left to right direction

skinparam{
    UsecaseBackgroundColor white
    UsecaseBorderColor black

    ArrowColor black

    Shadowing false 

    ActorBackgroundColor white
    ActorBorderColor black
}

rectangle Lobby {
    (Regestrieren) as Reg
    (Einloggen) as Login
    (Ausloggen) as Logout
    (Spiel erstellen) as erstellen
    (Spiel beitreten) as beitreten
    (Spielregeln definieren) as regeln
    (Spiel starten) as start
    (Spiel verlassen) as verlassen
}

actor :Spieler: as Spieler
actor :Spiel-Ersteller: as Ersteller

Ersteller --|> Spieler

Spieler -- erstellen
Spieler -- Reg
Spieler -- Login
Spieler -- Logout
Spieler -- beitreten
Spieler -- verlassen

Spieler -- start
Ersteller -- start
Ersteller -- regeln

Reg .> Login : <<include>>
verlassen .> Logout : <<extends>>

verlassen .> beitreten :<<extends>>
erstellen .> regeln :<<include>>

start .> Logout : <<include>>
@enduml













